In [2]:
import pandas as pd
import csv
from collections import defaultdict

In [3]:
#split and append only disease name
def return_list(disease):
    disease_list = []
    match = disease.replace('^','_').split('_')
    ctr = 1
    for group in match:
        if ctr%2==0:
            disease_list.append(group)
        ctr = ctr + 1

    return disease_list

In [4]:
disease_list = []
with open("dis1.csv") as csvfile:
    reader = csv.reader(csvfile)
    
    disease=""
    weight = 0
    disease_list = []
    dict_wt = {}
    ####value is of type list
    dict_=defaultdict(list)
    
    for row in reader:
        #print(row)
        if row[0]!="\xc2\xa0" and row[0]!="":
            disease = row[0]
            disease_list = return_list(disease)
            weight = row[1]

        if row[2]!="\xc2\xa0" and row[2]!="":
            symptom_list = return_list(row[2])
            ####appending disease wise symptoms in dict_ and disease wise weights in dict_wt
            for d in disease_list:
                for s in symptom_list:
                    dict_[d].append(s)
                dict_wt[d] = weight
print(dict_)
print('---------------------')
print(dict_wt)
print('======================')

defaultdict(<class 'list'>, {'hypertensive disease': ['pain chest', 'shortness of breath', 'dizziness', 'asthenia', 'fall', 'syncope', 'vertigo', 'sweat', 'sweating increased', 'palpitation', 'nausea', 'angina pectoris', 'pressure chest'], 'diabetes': ['polyuria', 'polydypsia', 'shortness of breath', 'pain chest', 'asthenia', 'nausea', 'orthopnea', 'rale', 'sweat', 'sweating increased', 'unresponsiveness', 'mental status changes', 'vertigo', 'vomiting', 'labored breathing'], 'depression mental': ['feeling suicidal', 'suicidal', 'hallucinations auditory', 'feeling hopeless', 'weepiness', 'sleeplessness', 'motor retardation', 'irritable mood', 'blackout', 'mood depressed', 'hallucinations visual', 'worry', 'agitation', 'tremor', 'intoxication', 'verbal auditory hallucinations', 'energy increased', 'difficulty', 'nightmare', 'unable to concentrate', 'homelessness'], 'depressive disorder': ['feeling suicidal', 'suicidal', 'hallucinations auditory', 'feeling hopeless', 'weepiness', 'sleeple

In [5]:
###cleaning data by filling each column of each row by repective disease and weights.
with open("dis.csv","w") as csvfile:
    writer = csv.writer(csvfile)
    for key,values in dict_.items():
        for v in values:
            key = str.encode(key).decode('utf-8')
            writer.writerow([key,v,dict_wt[key]])


In [6]:
col = ['Source','Target','Weight']

In [7]:
data = pd.read_csv("dis.csv",names=col, encoding ="ISO-8859-1")
data.head(4)

Source               Target  Weight
0  hypertensive disease           pain chest    3363
1  hypertensive disease  shortness of breath    3363
2  hypertensive disease            dizziness    3363
3  hypertensive disease             asthenia    3363

In [8]:
data.to_csv("dis.csv",index=False)

In [9]:
##assigning keyword is a disease or a symptom
symp_list = []
dis_list = []
with open("nodetable.csv","w") as csvfile:
    writer = csv.writer(csvfile)

    for key,values in dict_.items():
        for v in values:
            if v not in symp_list:
                writer.writerow([v,v,"symptom"])
                symp_list.append(v)
        if key not in dis_list:
            writer.writerow([key,key,"disease"])
            dis_list.append(key)
dis_list

['hypertensive disease',
 'diabetes',
 'depression mental',
 'depressive disorder',
 'coronary arteriosclerosis',
 'coronary heart disease',
 'pneumonia',
 'failure heart congestive',
 'accident cerebrovascular',
 'asthma',
 'myocardial infarction',
 'hypercholesterolemia',
 'infection',
 'infection urinary tract',
 'anemia',
 'chronic obstructive airway disease',
 'dementia',
 'insufficiency renal',
 'confusion',
 'degenerative polyarthritis',
 'hypothyroidism',
 'anxiety state',
 'malignant neoplasms',
 'primary malignant neoplasm',
 'acquired immuno-deficiency syndrome',
 'HIV',
 'hiv infections',
 'cellulitis',
 'gastroesophageal reflux disease',
 'septicemia',
 'systemic infection',
 'sepsis (invertebrate)',
 'deep vein thrombosis',
 'dehydration',
 'neoplasm',
 'embolism pulmonary',
 'epilepsy',
 'cardiomyopathy',
 'chronic kidney failure',
 'carcinoma',
 'hepatitis C',
 'peripheral vascular disease',
 'psychotic disorder',
 'hyperlipidemia',
 'bipolar disorder',
 'obesity',
 'is

In [10]:
print(len(dis_list))
print(len(symp_list))

148
405


In [11]:
new_col = ['Id','Label','Attribute']
new_data = pd.read_csv("nodetable.csv",names=new_col, encoding ="ISO-8859-1")
new_data.head()

Id                Label Attribute
0           pain chest           pain chest   symptom
1  shortness of breath  shortness of breath   symptom
2            dizziness            dizziness   symptom
3             asthenia             asthenia   symptom
4                 fall                 fall   symptom

In [12]:
new_data[new_data['Attribute']=='disease'].head()

Id                      Label Attribute
13       hypertensive disease       hypertensive disease   disease
22                   diabetes                   diabetes   disease
44          depression mental          depression mental   disease
45        depressive disorder        depressive disorder   disease
49  coronary arteriosclerosis  coronary arteriosclerosis   disease

In [13]:
new_data.to_csv("nodetable.csv",index=False)
new_data.head()

Id                Label Attribute
0           pain chest           pain chest   symptom
1  shortness of breath  shortness of breath   symptom
2            dizziness            dizziness   symptom
3             asthenia             asthenia   symptom
4                 fall                 fall   symptom

In [14]:
##

In [15]:
data1 = pd.read_csv("dis.csv", encoding ="ISO-8859-1")
data1.head()

Source               Target  Weight
0  hypertensive disease           pain chest    3363
1  hypertensive disease  shortness of breath    3363
2  hypertensive disease            dizziness    3363
3  hypertensive disease             asthenia    3363
4  hypertensive disease                 fall    3363

In [16]:
#data contains clean data: symptom,corresponding disease and weight of disease
df = pd.DataFrame(data)
###https://www.geeksforgeeks.org/python-pandas-series-str-get_dummies/  read this link for get_dummies it is an amazing thing
df_1 = pd.get_dummies(df.Target)
df_1.head()

Heberden's node  Murphy's sign  Stahli's line  abdomen acute  \
0                0              0              0              0   
1                0              0              0              0   
2                0              0              0              0   
3                0              0              0              0   
4                0              0              0              0   

   abdominal bloating  abdominal tenderness  abnormal sensation  \
0                   0                     0                   0   
1                   0                     0                   0   
2                   0                     0                   0   
3                   0                     0                   0   
4                   0                     0                   0   

   abnormally hard consistency  abortion  abscess bacterial  ...  \
0                            0         0                  0  ...   
1                            0         0                  0  ...   
2                            0         0                  0  ...   
3                            0         0                  0  ...   
4                            0         0                  0  ...   

   vision blurred  vomiting  weepiness  weight gain  welt  wheelchair bound  \
0               0         0          0            0     0                 0   
1               0         0          0            0     0                 0   
2               0         0          0            0     0                 0   
3               0         0          0            0     0                 0   
4               0         0          0            0     0                 0   

   wheezing  withdraw  worry  yellow sputum  
0         0         0      0              0  
1         0         0      0              0  
2         0         0      0              0  
3         0         0      0              0  
4         0         0      0              0  

[5 rows x 404 columns]

In [17]:
df_s = df['Source']
####arranging source(i.e disease with presence or absence of symptoms)
df_pivoted = pd.concat([df_s,df_1], axis=1)
##alternative for below::: df_pivoted = df_pivoted[~df_pivoted.duplicated()]
df_pivoted.drop_duplicates(keep='first',inplace=True)
df_pivoted.head()
#print(df_pi)

Source  Heberden's node  Murphy's sign  Stahli's line  \
0  hypertensive disease                0              0              0   
1  hypertensive disease                0              0              0   
2  hypertensive disease                0              0              0   
3  hypertensive disease                0              0              0   
4  hypertensive disease                0              0              0   

   abdomen acute  abdominal bloating  abdominal tenderness  \
0              0                   0                     0   
1              0                   0                     0   
2              0                   0                     0   
3              0                   0                     0   
4              0                   0                     0   

   abnormal sensation  abnormally hard consistency  abortion  ...  \
0                   0                            0         0  ...   
1                   0                            0         0  ...   
2                   0                            0         0  ...   
3                   0                            0         0  ...   
4                   0                            0         0  ...   

   vision blurred  vomiting  weepiness  weight gain  welt  wheelchair bound  \
0               0         0          0            0     0                 0   
1               0         0          0            0     0                 0   
2               0         0          0            0     0                 0   
3               0         0          0            0     0                 0   
4               0         0          0            0     0                 0   

   wheezing  withdraw  worry  yellow sputum  
0         0         0      0              0  
1         0         0      0              0  
2         0         0      0              0  
3         0         0      0              0  
4         0         0      0              0  

[5 rows x 405 columns]

In [18]:
cols = df_pivoted.columns
####starting from 1st index contains all columns
cols=cols[1:]

In [19]:
###grouping wrt disease
df_pivoted = df_pivoted.groupby('Source').sum()
df_pivoted = df_pivoted.reset_index()
df_pivoted[:5]

Source  Heberden's node  Murphy's sign  \
0                  Alzheimer's disease                0              0   
1                                  HIV                0              0   
2       Pneumocystis carinii pneumonia                0              0   
3             accident cerebrovascular                0              0   
4  acquired immuno-deficiency syndrome                0              0   

   Stahli's line  abdomen acute  abdominal bloating  abdominal tenderness  \
0              0              0                   0                     0   
1              0              0                   0                     0   
2              0              0                   0                     0   
3              0              0                   0                     0   
4              0              0                   0                     0   

   abnormal sensation  abnormally hard consistency  abortion  ...  \
0                   0                            0         0  ...   
1                   0                            0         0  ...   
2                   0                            0         0  ...   
3                   0                            0         0  ...   
4                   0                            0         0  ...   

   vision blurred  vomiting  weepiness  weight gain  welt  wheelchair bound  \
0               0         0          0            0     0                 1   
1               0         0          0            0     0                 0   
2               0         0          0            0     0                 0   
3               0         0          0            0     0                 0   
4               0         0          0            0     0                 0   

   wheezing  withdraw  worry  yellow sputum  
0         0         0      0              0  
1         0         0      0              0  
2         0         0      0              1  
3         0         0      0              0  
4         0         0      0              0  

[5 rows x 405 columns]

In [20]:
df_pivoted.to_csv("df_pivoted.csv")

In [21]:
x = df_pivoted[cols]
y = df_pivoted['Source']
y.head()

0                    Alzheimer's disease
1                                    HIV
2         Pneumocystis carinii pneumonia
3               accident cerebrovascular
4    acquired immuno-deficiency syndrome
Name: Source, dtype: object

# Naive Bayes on cleaned dataset

In [22]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [23]:
####use k-fold cross validation
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)


In [24]:
from sklearn.metrics import accuracy_score
##multinomial Naive Bayes also called Conditional probablity
##if I am interested in finding frequency of a particular word in a text file there multinomial Naive Bayes is used.
##it is used to evaluate combined probablity suppose you have 6 people, u need to find combined prob of 1 having O blood group, 2 having A bg, 2 having B bg, 1 having AB bg
##you do this by p(x1=1 and x2=2 and x3=2 and x4=1) = (6!/1!*2!*2!*1!)*(p1^1)*(p2^2)*(p3^2)*(p4^1)
mnb = MultinomialNB()
mnb.fit(x_train, y_train)
y_pr = mnb.predict(x_test)
print(accuracy_score(y_test,y_pr))

0.0


In [25]:
##It can't work on unseen data because it has never seen that disease before. Also, there is only one point
#for each disease and hence no point for this. So we need to train the model entirely.
mnb_tot = MultinomialNB()
mnb_tot = mnb_tot.fit(x, y)
mnb_tot.score(x,y)

0.9054054054054054

In [26]:
disease_pred = mnb_tot.predict(x)
disease_real = y.values

In [27]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

con_mat = confusion_matrix(disease_real,disease_pred)
print(len(con_mat))
print('confusion_mat:')
print(con_mat)
print('accuracy: ')
print(accuracy_score(disease_real,disease_pred))
print('classify: ')
print(classification_report(disease_real,disease_pred))

148
confusion_mat:
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
accuracy: 
0.9054054054054054
classify: 
                                      precision    recall  f1-score   support

                 Alzheimer's disease       1.00      1.00      1.00         1
                                 HIV       0.33      1.00      0.50         1
      Pneumocystis carinii pneumonia       1.00      1.00      1.00         1
            accident cerebrovascular       1.00      1.00      1.00         1
 acquired immuno-deficiency syndrome       0.00      0.00      0.00         1
                      adenocarcinoma       1.00      1.00      1.00         1
                            adhesion       1.00      1.00      1.00         1
                       affect labile       1.00      1.00      1.00         1
                              anemia       1.00      1.00      1.00         1
                       anxiety state   

C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [28]:
#print those not match to real
for i in range(0, len(disease_real)):
    if disease_pred[i]!=disease_real[i]:
        print ('Pred: {0} Actual:{1}'.format(disease_pred[i], disease_real[i]))

Pred: HIV Actual:acquired immuno-deficiency syndrome
Pred: biliary calculus Actual:cholelithiasis
Pred: coronary arteriosclerosis Actual:coronary heart disease
Pred: depression mental Actual:depressive disorder
Pred: HIV Actual:hiv infections
Pred: carcinoma breast Actual:malignant neoplasm of breast
Pred: carcinoma of lung Actual:malignant neoplasm of lung
Pred: carcinoma prostate Actual:malignant neoplasm of prostate
Pred: carcinoma colon Actual:malignant tumor of colon
Pred: candidiasis Actual:oral candidiasis
Pred: effusion pericardial Actual:pericardial effusion body substance
Pred: sepsis (invertebrate) Actual:septicemia
Pred: sepsis (invertebrate) Actual:systemic infection
Pred: tonic-clonic epilepsy Actual:tonic-clonic seizures


# Decision tree classifier on cleaned dataset

In [32]:
from sklearn.tree import DecisionTreeClassifier
print ("DecisionTree")
dt = DecisionTreeClassifier()
clf_dt=dt.fit(x,y)
#print ("Acurracy: ", clf_dt.score(x,y))

DecisionTree


In [33]:
disease_real_d = y.values
disease_pred_d = clf_dt.predict(x)

In [34]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

con_mat_d = confusion_matrix(disease_real_d,disease_pred_d)
print(len(con_mat_d))
print('confusion_mat:')
print(con_mat_d)
print('accuracy: ')
print(accuracy_score(disease_real_d,disease_pred_d))
print('classify: ')
print(classification_report(disease_real_d,disease_pred_d))

148
confusion_mat:
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
accuracy: 
0.9054054054054054
classify: 
                                      precision    recall  f1-score   support

                 Alzheimer's disease       1.00      1.00      1.00         1
                                 HIV       0.33      1.00      0.50         1
      Pneumocystis carinii pneumonia       1.00      1.00      1.00         1
            accident cerebrovascular       1.00      1.00      1.00         1
 acquired immuno-deficiency syndrome       0.00      0.00      0.00         1
                      adenocarcinoma       1.00      1.00      1.00         1
                            adhesion       1.00      1.00      1.00         1
                       affect labile       1.00      1.00      1.00         1
                              anemia       1.00      1.00      1.00         1
                       anxiety state   

C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Naive Bayes on manual training dataset

In [65]:
#manual data analysis
data = pd.read_csv("Training.csv")
data.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [66]:
len(data['prognosis'].unique())

41

In [67]:
df = pd.DataFrame(data)
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          1   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       1           1             1        1                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        1                 1  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [68]:
cols = df.columns
cols = cols[:-1]
len(cols)

132

In [69]:
x = df[cols]
y = df['prognosis']

In [70]:
###train_test_split uniformly distributes repeated data hence accuracy will be 1
x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(x, y, test_size=0.33, random_state=42)
#print(len(y_test_1.unique()))
#print(len(y_train_1.unique()))
mnb1 = MultinomialNB()
mnb1 = mnb1.fit(x_train_1, y_train_1)
mnb1.score(x_test_1,y_test_1)

1.0

In [72]:
#k_fold_cross_validation
#on testing.csv 
#testx and testy are varibales for testing.csv
from sklearn import model_selection
print ("cross result for naive bayes on manual training========")
scores = model_selection.cross_val_score(mnb1,x,y, cv=3)
print (scores)
print (scores.mean())

cross result for naive bayes on manual training========
[1. 1. 1.]
1.0


# Naive Bayes on manual testing data

In [53]:
from sklearn import model_selection

In [54]:
test_data = pd.read_csv("Testing.csv")
test_data.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze            prognosis  
0                  0     Fungal infection  
1                  0              Allergy  
2                  0                 GERD  
3                  0  Chronic cholestasis  
4                  0        Drug Reaction  

[5 rows x 133 columns]

In [99]:
testx = test_data[cols]
testy = test_data['prognosis']
mnb1.score(testx, testy)

1.0

In [79]:
features_mnb1 = cols
feature_dict_mnb1 = {}
for i,f in enumerate(features_mnb1):
    feature_dict_mnb1[f] = i
feature_dict_mnb1

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelle

In [87]:
num_mnb1=feature_dict_mnb1['muscle_pain']
num1_mnb1 = feature_dict_mnb1['fatigue']
num2_mnb1 = feature_dict_mnb1['cold_hands_and_feets']

sample_x_mnb1 = [1 if (i ==num_mnb1 or i==num1_mnb1 or i==num2_mnb1) else 0 for i in range(len(features_mnb1))]

sample_x_mnb1 = np.array(sample_x_mnb1).reshape(1,len(sample_x_mnb1))
dt.predict(sample_x_mnb1)

array(['Malaria'], dtype=object)

# Decision tree on Manual training data

In [62]:
##x and y are trainig.csv variables
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

print ("DecisionTree")
dt = DecisionTreeClassifier()
clf_dt=dt.fit(x_train,y_train)
#print ("Acurracy: ", clf_dt.score(x_test,y_test))

DecisionTree


In [75]:
#k_fold_cross_validation
#on testing.csv 
from sklearn import model_selection
print ("cross result for decision classidfier on manual training========")
scores = model_selection.cross_val_score(dt, x, y, cv=3)
print (scores)
print (scores.mean())

cross result for decision classidfier on manual training========
[0.99878049 1.         1.        ]
0.9995934959349594


# Decision classifier on manual testing

In [580]:
#find_importance_of_feature
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

importances = dt.feature_importances_
indices = np.argsort(importances)[::-1]


In [581]:
features = cols
for f in range(10):
    print("%d. feature %d - %s (%f)" % (f + 1, indices[f], features[indices[f]] ,importances[indices[f]]))

1. feature 53 - sinus_pressure (0.026703)
2. feature 93 - internal_itching (0.026649)
3. feature 79 - hip_joint_pain (0.026626)
4. feature 104 - increased_appetite (0.026390)
5. feature 126 - silver_like_dusting (0.025712)
6. feature 72 - brittle_nails (0.025479)
7. feature 118 - blood_in_sputum (0.024874)
8. feature 131 - yellow_crust_ooze (0.024798)
9. feature 2 - nodal_skin_eruptions (0.024735)
10. feature 86 - unsteadiness (0.024486)


In [624]:
feature_dict = {}
for i,f in enumerate(features):
    feature_dict[f] = i
feature_dict

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelle

In [625]:
num=feature_dict['muscle_pain']
num1 = feature_dict['fatigue']
num2 = feature_dict['cold_hands_and_feets']

In [626]:
sample_x = [1 if (i ==num or i==num1 or i==num2) else 0 for i in range(len(features))]

In [91]:
sample_x = np.array(sample_x).reshape(1,len(sample_x))
dt.predict(sample_x)

array(['Malaria'], dtype=object)

# svm on manual training

In [92]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(x_train, y_train)
#y_pred = svclassifier.predict(x_test)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [93]:
from sklearn import model_selection
print ("cross result for svm classidfier on manual training========")
scores = model_selection.cross_val_score(dt, x, y, cv=3)
print (scores)
print (scores.mean())

cross result for svm classidfier on manual training========
[0.99939024 1.         1.        ]
0.9997967479674797


# svm on manual testing

In [94]:
features_svm = cols
feature_dict_svm = {}
for i,f in enumerate(features_svm):
    feature_dict_svm[f] = i
feature_dict_svm

{'itching': 0,
 'skin_rash': 1,
 'nodal_skin_eruptions': 2,
 'continuous_sneezing': 3,
 'shivering': 4,
 'chills': 5,
 'joint_pain': 6,
 'stomach_pain': 7,
 'acidity': 8,
 'ulcers_on_tongue': 9,
 'muscle_wasting': 10,
 'vomiting': 11,
 'burning_micturition': 12,
 'spotting_ urination': 13,
 'fatigue': 14,
 'weight_gain': 15,
 'anxiety': 16,
 'cold_hands_and_feets': 17,
 'mood_swings': 18,
 'weight_loss': 19,
 'restlessness': 20,
 'lethargy': 21,
 'patches_in_throat': 22,
 'irregular_sugar_level': 23,
 'cough': 24,
 'high_fever': 25,
 'sunken_eyes': 26,
 'breathlessness': 27,
 'sweating': 28,
 'dehydration': 29,
 'indigestion': 30,
 'headache': 31,
 'yellowish_skin': 32,
 'dark_urine': 33,
 'nausea': 34,
 'loss_of_appetite': 35,
 'pain_behind_the_eyes': 36,
 'back_pain': 37,
 'constipation': 38,
 'abdominal_pain': 39,
 'diarrhoea': 40,
 'mild_fever': 41,
 'yellow_urine': 42,
 'yellowing_of_eyes': 43,
 'acute_liver_failure': 44,
 'fluid_overload': 45,
 'swelling_of_stomach': 46,
 'swelle

In [95]:
num_svm=feature_dict_svm['muscle_pain']
num1_svm = feature_dict_svm['fatigue']
num2_svm = feature_dict_svm['cold_hands_and_feets']

sample_x_svm= [1 if (i ==num_svm or i==num1_svm or i==num2_svm) else 0 for i in range(len(features_svm))]

sample_x_svm = np.array(sample_x_svm).reshape(1,len(sample_x_svm))
dt.predict(sample_x_svm)

array(['Malaria'], dtype=object)